import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const appDir = path.resolve(scriptDir, "..");
const repoRoot = path.resolve(appDir, "../..");
const generatedDir = path.join(appDir, "src", "generated");
const publicDir = path.join(appDir, "public");
const publicSourceDir = path.join(publicDir, "source");

const excludedRootDirs = new Set([".git", "apps", "docs", "node_modules"]);
const slugPattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const idPattern = /^[a-zA-Z][a-zA-Z0-9]*$/;

await main();

async function main() {
  const toolDirs = await findToolDirs();
  if (toolDirs.length === 0) {
    throw new Error("No tool.config.json files found at repository root.");
  }

  await fs.rm(publicSourceDir, { recursive: true, force: true });
  await fs.mkdir(generatedDir, { recursive: true });
  await fs.mkdir(publicSourceDir, { recursive: true });

  const tools = [];
  const sourceFiles = {};
  const slugs = new Set();

  for (const toolDir of toolDirs) {
    const configPath = path.join(toolDir, "tool.config.json");
    const readmePath = path.join(toolDir, "readme.md");
    const config = await readJson(configPath);
    const readme = await fs.readFile(readmePath, "utf8");

    validateToolConfig(config, configPath);
    if (slugs.has(config.slug)) {
      throw new Error(`Duplicate tool slug: ${config.slug}`);
    }
    slugs.add(config.slug);

    const normalizedSources = [];
    const sourceIds = new Set();

    for (const source of config.sourceFiles) {
      if (sourceIds.has(source.id)) {
        throw new Error(`${config.slug}: duplicate source file id ${source.id}`);
      }
      sourceIds.add(source.id);

      const normalizedSource = normalizeSourceFile(config.slug, toolDir, source);
      normalizedSources.push(normalizedSource);

      if (sourceFiles[normalizedSource.route]) {
        throw new Error(`Duplicate source route: ${normalizedSource.route}`);
      }
      sourceFiles[normalizedSource.route] = normalizedSource;

      if (normalizedSource.delivery === "asset") {
        await copySourceAsset(config.slug, toolDir, normalizedSource);
      }
    }

    for (const command of config.commands) {
      validateCommandTemplate(config.slug, command, sourceIds);
    }

    tools.push({
      slug: config.slug,
      route: `/tools/${config.slug}`,
      title: config.title,
      category: config.category,
      summary: config.summary,
      platforms: config.platforms,
      tags: config.tags,
      order: config.order,
      accent: config.accent,
      readmeHtml: renderMarkdown(readme),
      sourceFiles: normalizedSources,
      commands: config.commands
    });
  }

  tools.sort((a, b) => a.order - b.order || a.title.localeCompare(b.title));
  const generated = `// Generated by npm run build:tools. Do not edit manually.\n\nimport type { SourceFile, ToolPage } from "../tools.ts";\n\nexport const sourceFiles: Record<string, SourceFile> = ${JSON.stringify(sourceFiles, null, 2)};\n\nexport const toolPages: ToolPage[] = ${JSON.stringify(tools, null, 2)};\n`;
  await fs.writeFile(path.join(generatedDir, "tools.ts"), generated, "utf8");

  console.log(`Generated ${tools.length} tools and ${Object.keys(sourceFiles).length} source routes.`);
}

async function findToolDirs() {
  const entries = await fs.readdir(repoRoot, { withFileTypes: true });
  const toolDirs = [];

  for (const entry of entries) {
    if (!entry.isDirectory() || excludedRootDirs.has(entry.name)) {
      continue;
    }

    const dir = path.join(repoRoot, entry.name);
    if (await fileExists(path.join(dir, "tool.config.json"))) {
      if (!(await fileExists(path.join(dir, "readme.md")))) {
        throw new Error(`${entry.name} has tool.config.json but no readme.md.`);
      }
      toolDirs.push(dir);
    }
  }

  return toolDirs;
}

async function readJson(filePath) {
  try {
    return JSON.parse(await fs.readFile(filePath, "utf8"));
  } catch (error) {
    throw new Error(`Failed to read ${filePath}: ${formatError(error)}`);
  }
}

async function fileExists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

function validateToolConfig(config, configPath) {
  const prefix = `${configPath}:`;
  assertString(config.slug, `${prefix} slug`);
  if (!slugPattern.test(config.slug)) {
    throw new Error(`${prefix} slug must use lowercase kebab-case.`);
  }

  assertString(config.title, `${prefix} title`);
  assertString(config.category, `${prefix} category`);
  assertString(config.summary, `${prefix} summary`);
  assertString(config.accent, `${prefix} accent`);
  if (!["emerald", "sky", "amber"].includes(config.accent)) {
    throw new Error(`${prefix} accent must be emerald, sky, or amber.`);
  }
  assertArrayOfStrings(config.platforms, `${prefix} platforms`);
  assertArrayOfStrings(config.tags, `${prefix} tags`);
  if (!Number.isInteger(config.order)) {
    throw new Error(`${prefix} order must be an integer.`);
  }

  if (!Array.isArray(config.sourceFiles) || config.sourceFiles.length === 0) {
    throw new Error(`${prefix} sourceFiles must be a non-empty array.`);
  }
  if (!Array.isArray(config.commands) || config.commands.length === 0) {
    throw new Error(`${prefix} commands must be a non-empty array.`);
  }

  for (const source of config.sourceFiles) {
    assertString(source.id, `${prefix} sourceFiles[].id`);
    assertString(source.path, `${prefix} sourceFiles[].path`);
    assertString(source.route, `${prefix} sourceFiles[].route`);
    assertString(source.filename, `${prefix} sourceFiles[].filename`);
    assertString(source.contentType, `${prefix} sourceFiles[].contentType`);
    assertString(source.label, `${prefix} sourceFiles[].label`);
    assertString(source.delivery, `${prefix} sourceFiles[].delivery`);
    if (!idPattern.test(source.id)) {
      throw new Error(`${prefix} source id ${source.id} must be camelCase/alphanumeric.`);
    }
    if (!["asset", "remote"].includes(source.delivery)) {
      throw new Error(`${prefix} source ${source.id} delivery must be asset or remote.`);
    }
    if (source.delivery === "remote" && source.envKey === undefined) {
      throw new Error(`${prefix} remote source ${source.id} must define envKey.`);
    }
    if (source.envKey !== undefined) {
      assertString(source.envKey, `${prefix} sourceFiles[].envKey`);
    }
  }

  const commandIds = new Set();
  for (const command of config.commands) {
    assertString(command.id, `${prefix} commands[].id`);
    if (commandIds.has(command.id)) {
      throw new Error(`${prefix} duplicate command id ${command.id}`);
    }
    commandIds.add(command.id);

    assertString(command.title, `${prefix} commands[].title`);
    assertString(command.description, `${prefix} commands[].description`);
    assertString(command.platform, `${prefix} commands[].platform`);
    assertString(command.language, `${prefix} commands[].language`);
    assertString(command.template, `${prefix} commands[].template`);
    if (!["bash", "powershell"].includes(command.language)) {
      throw new Error(`${prefix} command ${command.id} language must be bash or powershell.`);
    }
    if (command.badges !== undefined) {
      assertArrayOfStrings(command.badges, `${prefix} commands[].badges`);
    }
    if (command.inputs !== undefined) {
      validateInputs(command.inputs, `${prefix} command ${command.id}`);
    }
  }
}

function validateInputs(inputs, prefix) {
  if (!Array.isArray(inputs)) {
    throw new Error(`${prefix} inputs must be an array.`);
  }

  const inputIds = new Set();
  for (const input of inputs) {
    assertString(input.id, `${prefix} inputs[].id`);
    if (!idPattern.test(input.id)) {
      throw new Error(`${prefix} input id ${input.id} must be camelCase/alphanumeric.`);
    }
    if (inputIds.has(input.id)) {
      throw new Error(`${prefix} duplicate input id ${input.id}`);
    }
    inputIds.add(input.id);

    assertString(input.label, `${prefix} inputs[].label`);
    assertString(input.placeholder, `${prefix} inputs[].placeholder`);
    assertString(input.type, `${prefix} inputs[].type`);
    assertString(input.quote, `${prefix} inputs[].quote`);
    if (!["password", "text"].includes(input.type)) {
      throw new Error(`${prefix} input ${input.id} type must be password or text.`);
    }
    if (input.quote !== "posix") {
      throw new Error(`${prefix} input ${input.id} quote must be posix.`);
    }
  }
}

function normalizeSourceFile(toolSlug, toolDir, source) {
  if (!source.route.startsWith(`/source/${toolSlug}/`)) {
    throw new Error(`${toolSlug}: source route ${source.route} must start with /source/${toolSlug}/.`);
  }

  const sourcePath = path.resolve(toolDir, source.path);
  if (!sourcePath.startsWith(`${path.resolve(toolDir)}${path.sep}`)) {
    throw new Error(`${toolSlug}: source path escapes tool directory: ${source.path}`);
  }

  const publicPath = path.resolve(publicDir, `.${source.route}`);
  if (!publicPath.startsWith(`${publicSourceDir}${path.sep}`)) {
    throw new Error(`${toolSlug}: source route escapes public/source: ${source.route}`);
  }

  return {
    id: source.id,
    toolSlug,
    path: source.path,
    route: source.route,
    filename: source.filename,
    contentType: source.contentType,
    label: source.label,
    delivery: source.delivery,
    envKey: source.envKey
  };
}

async function copySourceAsset(toolSlug, toolDir, source) {
  const from = path.resolve(toolDir, source.path);
  const to = path.resolve(publicDir, `.${source.route}`);

  if (!(await fileExists(from))) {
    throw new Error(`${toolSlug}: source file not found: ${source.path}`);
  }

  await fs.mkdir(path.dirname(to), { recursive: true });
  await fs.copyFile(from, to);
}

function validateCommandTemplate(toolSlug, command, sourceIds) {
  const inputIds = new Set(command.inputs?.map((input) => input.id) ?? []);
  const placeholders = command.template.matchAll(/\{\{([^}]+)\}\}/g);

  for (const match of placeholders) {
    const placeholder = match[1];
    if (placeholder.startsWith("source:")) {
      const sourceId = placeholder.slice("source:".length);
      if (!sourceIds.has(sourceId)) {
        throw new Error(`${toolSlug}: command ${command.id} references unknown source ${sourceId}.`);
      }
      continue;
    }

    if (!inputIds.has(placeholder)) {
      throw new Error(`${toolSlug}: command ${command.id} references unknown input ${placeholder}.`);
    }
  }
}

function renderMarkdown(markdown) {
  const lines = markdown.replace(/\r\n/g, "\n").split("\n");
  const html = [];
  const paragraph = [];
  const listItems = [];
  const codeLines = [];
  let inCode = false;
  let codeLanguage = "";
  let skippedFirstH1 = false;

  const flushParagraph = () => {
    if (paragraph.length === 0) {
      return;
    }
    html.push(`<p>${renderInline(paragraph.join(" "))}</p>`);
    paragraph.length = 0;
  };

  const flushList = () => {
    if (listItems.length === 0) {
      return;
    }
    html.push(`<ul>${listItems.map((item) => `<li>${renderInline(item)}</li>`).join("")}</ul>`);
    listItems.length = 0;
  };

  const flushCode = () => {
    const langAttr = codeLanguage ? ` data-lang="${escapeAttr(codeLanguage)}"` : "";
    html.push(`<pre><code${langAttr}>${escapeHtml(codeLines.join("\n"))}</code></pre>`);
    codeLines.length = 0;
    codeLanguage = "";
  };

  for (const line of lines) {
    if (inCode) {
      if (line.trim().startsWith("```")) {
        flushCode();
        inCode = false;
      } else {
        codeLines.push(line);
      }
      continue;
    }

    const trimmed = line.trim();
    if (trimmed.startsWith("```")) {
      flushParagraph();
      flushList();
      inCode = true;
      codeLanguage = trimmed.slice(3).trim();
      continue;
    }

    if (trimmed === "") {
      flushParagraph();
      flushList();
      continue;
    }

    const heading = trimmed.match(/^(#{1,4})\s+(.+)$/);
    if (heading) {
      flushParagraph();
      flushList();
      const level = heading[1].length;
      if (level === 1 && !skippedFirstH1) {
        skippedFirstH1 = true;
        continue;
      }
      const renderedLevel = Math.min(level + 1, 4);
      html.push(`<h${renderedLevel}>${renderInline(heading[2])}</h${renderedLevel}>`);
      continue;
    }

    const listItem = trimmed.match(/^-\s+(.+)$/);
    if (listItem) {
      flushParagraph();
      listItems.push(listItem[1]);
      continue;
    }

    flushList();
    paragraph.push(trimmed);
  }

  if (inCode) {
    flushCode();
  }
  flushParagraph();
  flushList();

  return html.join("\n");
}

function renderInline(value) {
  const parts = value.split(/(`[^`]+`)/g);
  return parts
    .map((part) => {
      if (part.startsWith("`") && part.endsWith("`")) {
        return `<code>${escapeHtml(part.slice(1, -1))}</code>`;
      }
      return escapeHtml(part).replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_match, text, href) => {
        const safeHref = sanitizeHref(href);
        if (!safeHref) {
          return text;
        }
        return `<a href="${escapeAttr(safeHref)}">${text}</a>`;
      });
    })
    .join("");
}

function sanitizeHref(href) {
  if (/^(https?:\/\/|\/|#)/.test(href)) {
    return href;
  }
  return "";
}

function assertString(value, label) {
  if (typeof value !== "string" || value.trim() === "") {
    throw new Error(`${label} must be a non-empty string.`);
  }
}

function assertArrayOfStrings(value, label) {
  if (!Array.isArray(value) || value.length === 0 || value.some((item) => typeof item !== "string" || item.trim() === "")) {
    throw new Error(`${label} must be a non-empty string array.`);
  }
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escapeAttr(value) {
  return escapeHtml(value).replace(/\n/g, "&#10;");
}

function formatError(error) {
  return error instanceof Error ? error.message : String(error);
}
